# Generated by Django 5.0.7 on 2024-07-18 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=4)),
                ('imdbRating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('Poster', models.URLField()),
                ('Plot', models.TextField()),
                ('Actors', models.TextField()),
                ('Director', models.TextField()),
                ('Released', models.TextField()),
                ('Genre', models.TextField()),
                ('Runtime', models.TextField()),
            ],
        ),
    ]
